### ISSUE TITLE
lastIn/lastOut is always Zero

### ISSUE THREAD

**Issue by uaalto** [getlantern/measured#3]

**Comment by uaalto** [comment]
I've tried first assuming that this is working and has been tested, but there are no specific tests for this. Should we create one?

**Comment by fffw** [comment]
It depends on how the connection is handled. I think Lantern server never actively closes connection, so if client makes requests without `DisableKeepAlives=true`, it will keep connection until finally cut off by idle timing or the site to visit. The idle timeout of Lantern client is 1 hour, so `lastIn/lastOut` is very likely to be zero because of inactivity. `curl -vLk https://<proxy address> -H "X-Lantern-Device-Id: xxx"` directly would trigger non-zero `lastIn/lastOut` I guess?

Sure I can update the test, as I'm also going to extract `measured` as a struct from global namespace.

**Comment by fffw** [comment]
Added test to check `lastIn/lastOut` at https://github.com/getlantern/measured/pull/4/commits/55a31b452efe54901ca67f7892e60a06c2b5f051

**Comment by uaalto** [comment]
Total bytes gets, however, updated. So this means that only after the bytes stop being recorded in the first time period and get to the next time period, we will have 0 lastIn/lastOut, but will have the fresh total always.
Can we assume that `totalIn - lastIn = current period In`?

**Comment by uaalto** [comment]
I wanted to mention also that I had the understanding that lastIn/lastOut represent the number of bytes since the last reporting. That would really simplify logic for the user of the library for most cases.

**Comment by fffw** [comment]
@uaalto All fields are calculated based on all collected datapoints within single report period, so lastIn/lastOut is just the last datapoint, and totalIn/totalOut is what you actually want---number of bytes in current report period. Other fields are mostly for speed measurements

**Comment by uaalto** [comment]
oooh, so I got it all backwards ;D
So, what you are saying is that every time I request a report, I can increment by totalIn/totalOut to the corresponding key in Redis and that would reflect the correct historical totals, because they will always be relative to the previous reporting, right?
If that's the case, I think the naming is confusing, but now that I know it's fine :)

One thing is not completely clear to me then: If lastIn/Out are the last datapoints (not the totals of the previous report period), when are they actually sampling? How and when are they used? In my current case, you say that they'll be zero because the connection doesn't close. But when is closed, what's the use of lastIn/Out any more?

**Comment by fffw** [comment]
@uaalto I intended to show bps based on lastIn/Out divides the collect period, but it can also be derived from totalIn/Out divides report period, which is more smooth, so yes, it's not that useful.

**Comment by uaalto** [comment]
This is ok then. Thank you @fffw.
