### ISSUE TITLE
When measured is stopped, it still tries to collect statistics, leading to many errors messages

### ISSUE THREAD

**Issue by uaalto** [getlantern/measured#5]
The error is this, and also happens when you create a measured listener but do not start measured. I think in both cases measured look should avoid trying to submit.

```
Apr 26 20:00:27.112 ERROR measured: measured.go:439 Failed to submit traffic, channel busy
```

I propose a flag per connection to tell if its reporting or not, but perhaps you want a different approach @fffw .

**Comment by fffw** [comment]
Good catch @uaalto it should definitely be fixed.
